In [1]:

import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [ ]:
# code here
matrix = np.random.randint(0,100,12).reshape(4,3)

# sort it row-wise
# matrix = np.sort(matrix,axis=1)

# sort the 2nd col values
# indices = np.argsort(matrix[:,1],axis=0)
# sorted_matrix = matrix[indices]
# matrix

# sort row in ascending order
# max_values = np.max(matrix,axis=1)
# max_values
# indices = np.argsort(max_values)
# matrix = matrix[indices][::-1]
# matrix

# sort according to elements value
# matrix = np.sort(matrix,axis=1)
# matrix


array([[ 6,  6, 72],
       [20, 80, 96],
       [24, 67, 85],
       [ 3, 26, 31]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.


Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [ ]:
# # code here
# marks = np.array([[13, 10,  9, 33],
# 				  [63, 46, 90, 42],
# 				  [39, 76, 13, 29],
# 				  [82,  9, 29, 78],
# 				  [67, 61, 59, 36]
# 	   			],dtype=int)
# extra_subject_marks = [41,87,72,36,92]


# # Add extra subject marks to existing marks (same array)
# marks = np.append(marks,np.expand_dims(np.array(extra_subject_marks),1),axis=1)
# # marks

# # add 2 students record to that 5 subject record
# rec1 = [77, 83, 98, 95, 89]
# rec2 = [92, 71, 52, 61, 53]
# matrix = np.vstack((marks,rec1,rec2))
# matrix

# # add extra col with sum of all marks 
# sum_of_each_row = np.sum(matrix,axis=1)
# matrix = np.append(matrix,np.expand_dims(sum_of_each_row,axis=1),axis=1)
# # matrix

# # sort total marks col added recently

# # first sort the col itself so further we can get its indexes
# sorted_marks = np.sort(matrix[:,-1])[::-1]

# # we then need to collect it indexes
# sorted_marks_indices = np.argsort(sorted_marks)
# sorted_marks_indices

# # we will just mask it with original matrix
# matrix = matrix[sorted_marks_indices]
# # top 2 students
# matrix[0:2]



array([[ 92,  71,  52,  61,  53, 329],
       [ 77,  83,  98,  95,  89, 442]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
# code here

arr = np.array([
				[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]
			   ]
			  )

# unique elements row-wise

# unique_element_row_wise = np.unique(arr,axis=0)
# unique_element_row_wise

# unique elements col-wise
# unique_element_col_wise = np.unique(arr,axis=1)
# unique_element_col_wise



array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [ ]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

# flipping given 2d array along both axis at same time simply means not specifying and axis and use default mode of np.flip(arr)
# first flip all cols
# then flip all rows

arr = np.flip(arr)
arr

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [ ]:
# code here
arr = np.array([
	  [1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]
	  ])

X = 6

# since np.where returns tuple we extracted values from it
row_indices = np.where(np.any(arr > X,axis=1))[0]
row_indices


(array([1, 3]),)

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [84]:
# code here
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

arr_of_arrs = np.array([arr1,arr2,arr3],dtype=object)
# arr_of_arrs

flattened_res = np.concatenate((arr_of_arrs))
flattened_res


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [ ]:
# code here
# np.random.seed(400)
# arr = np.random.randint(100, 1000, 200).reshape((1, 200))
# print(arr)
# # this returns [num] therefore we extracted number from it using [0]
# min_element_idx = np.argmin(arr,axis=1)[0]
# min_element_idx
# max_element_idx = np.argmax(arr,axis=1)[0]
# max_element_idx
# arr = np.delete(arr,[min_element_idx,max_element_idx])
# arr

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]


array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320,
       230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587,
       227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879,
       575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395,
       525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976,
       786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621,
       453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 194, 76

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [96]:
# code here
arr = np.arange(100,701)
arr = np.clip(arr,a_min=100,a_max=200)
arr = np.sort(arr,kind='mergesort')
cum_sum = np.cumsum(arr)
cum_sum

array([   100,    201,    303,    406,    510,    615,    721,    828,
          936,   1045,   1155,   1266,   1378,   1491,   1605,   1720,
         1836,   1953,   2071,   2190,   2310,   2431,   2553,   2676,
         2800,   2925,   3051,   3178,   3306,   3435,   3565,   3696,
         3828,   3961,   4095,   4230,   4366,   4503,   4641,   4780,
         4920,   5061,   5203,   5346,   5490,   5635,   5781,   5928,
         6076,   6225,   6375,   6526,   6678,   6831,   6985,   7140,
         7296,   7453,   7611,   7770,   7930,   8091,   8253,   8416,
         8580,   8745,   8911,   9078,   9246,   9415,   9585,   9756,
         9928,  10101,  10275,  10450,  10626,  10803,  10981,  11160,
        11340,  11521,  11703,  11886,  12070,  12255,  12441,  12628,
        12816,  13005,  13195,  13386,  13578,  13771,  13965,  14160,
        14356,  14553,  14751,  14950,  15150,  15350,  15550,  15750,
        15950,  16150,  16350,  16550,  16750,  16950,  17150,  17350,
      

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [ ]:
arr = np.linspace(0, 1, 10)
arr = np.round(arr, 3)

print(np.percentile(arr, 0) == np.min(arr))
print(np.percentile(arr, 100) == np.max(arr))

diff_bw = np.percentile(arr, 51) - np.percentile(arr, 50)
print(diff_bw)

np.float64(0.010079999999999978)